CREATE TABLE users (
    UserID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TelegramID BIGINT UNIQUE NOT NULL,
    UserName VARCHAR(100),
    FirstName VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE products (
    ProductID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL,
    Price NUMERIC(10, 2) NOT NULL,
    Stock INT NOT NULL,
	ProductCategory VARCHAR(100) NOT NULL
);


CREATE TABLE orders (
    OrderID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    OrderStatus VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (UserID) REFERENCES users(UserID)
);


CREATE TABLE order_contents (
    OrderContentID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,

    FOREIGN KEY (OrderID) REFERENCES orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES products(ProductID)
);

CREATE TABLE carts (
    CartID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INT UNIQUE NOT NULL,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE
);

CREATE TABLE cart_items (
    CartItemID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CartID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),

    FOREIGN KEY (CartID) REFERENCES carts(CartID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES products(ProductID) ON DELETE CASCADE,
    CONSTRAINT unique_cart_product UNIQUE (CartID, ProductID)
);


CREATE TABLE support_requests (
    SupportRequestID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) NOT NULL DEFAULT 'open',

    FOREIGN KEY (UserID) REFERENCES users(UserID)
);


CREATE TABLE support_messages (
    SupportMessageID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SupportRequestID INT NOT NULL,
    SenderType VARCHAR(10) NOT NULL,
    Message TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (SupportRequestID)
        REFERENCES support_requests(SupportRequestID)
);